image: gitpod/workspace-full

tasks:
  - name: Run Java App
    init: |
      javac src/Main.java || true
    command: |
      clear
      echo "Compiling and running Project Scheduler..."
      javac src/Main.java
      java -cp src Main

vscode:
  extensions: []
